### ISSUE TITLE
usage of br tag

### ISSUE THREAD

**Issue by Rodrigap** [mkabobel/prj-rev-bwfs-dasmoto#1]
https://github.com/mkabobel/prj-rev-bwfs-dasmoto/blob/da44323191fcbe16b455080b64652bba96cf7880/Dasmoto's%20Arts%20%26%20Crafts/index.html#L9-L10

Instead of using multiple line break tags, try adding more of a bottom margin instead! This is way better practice

**Comment by mkabobel** [comment]
Got it, thanks!
