### ISSUE TITLE
Nice comments

### ISSUE THREAD

**Issue by Rodrigap** [mkabobel/prj-rev-bwfs-dasmoto#2]
https://github.com/mkabobel/prj-rev-bwfs-dasmoto/blob/da44323191fcbe16b455080b64652bba96cf7880/Dasmoto's%20Arts%20%26%20Crafts/index.html#L12

Nice job using HTML comments to label and separate your code! This makes it really easy for others to come in and read through and find specific sections. Great habit to get into

**Comment by mkabobel** [comment]
Thank you! Comments keep me sane.
