### ISSUE TITLE
Universal styles

### ISSUE THREAD

**Issue by Rodrigap** [mkabobel/prj-rev-bwfs-dasmoto#3]
https://github.com/mkabobel/prj-rev-bwfs-dasmoto/blob/da44323191fcbe16b455080b64652bba96cf7880/Dasmoto's%20Arts%20%26%20Crafts/resources/css/style.css#L1-L6

I see what you did here and I love that you made an effort to eliminate code repetition by putting this in! However, try using the body tag instead! It's slightly more concise and more commonly used:

```
body {
  font-family: "Helvetica";
}
```

**Comment by mkabobel** [comment]
Yeah, at first I had written it out that (body{}) way but it wasn't working, so I changed it (h1, h2, h3, p{}) thinking that was the issue - but I actually had an issue in my css link in the index.html file. Thank you for confirming what I originally thought!
