### ISSUE TITLE
Grade: Meets Expectations

### ISSUE THREAD

**Issue by Rodrigap** [mkabobel/prj-rev-bwfs-dasmoto#4]
Great job on this project! Your HTML and CSS all work well and look really good. I love that you added comments in your HTML (consider adding them in your CSS as well), and that you used appropriate HTML indentation and CSS spacing! Your finished product looks just like the spec, too. My biggest critique is with your use of the br HTML element tag. I would avoid getting in the habit of including so many of them (and especially of putting multiple in a row), just because it clutters up your HTML and isn't how that's normally used. Instead, just put your elements all next to each other add CSS to separate them more on the page. Overall, this is really good!

**Comment by mkabobel** [comment]
Great feedback! I'll make sure to not to get in the habit of using the br element tag like that.
